pool:
  vmImage: 'vs2017-win2016' # other options: 'Ubuntu 16.04', 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  packageVersion: '0.0.1'

steps:
- script: 
   dotnet restore
   dotnet build --configuration $(buildConfiguration)
   dotnet pack /p:PackageVersion=$(packageVersion) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1