pool:
  vmImage: 'vs2017-win2016' # other options: 'Ubuntu 16.04', 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  packageVersion: '0.0.1'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore 
    projects: '$(Parameters.RestoreBuildProjects)'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage" -s $(Build.SourcesDirectory)/samples/functionalTests.runsettings ' 
    continueOnError: true


- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack 
    nobuild: true 
    versioningScheme: byEnvVar
    versionEnvVar: packageVersion


- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'


- task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      